version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
